/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveysNewRouteImport } from './routes/surveys/new'
import { Route as SPublicIdRouteImport } from './routes/s/$publicId'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as SurveysIdResponsesRouteImport } from './routes/surveys/$id.responses'
import { Route as SurveysIdEditRouteImport } from './routes/surveys/$id.edit'
import { Route as SPublicIdThanksRouteImport } from './routes/s/$publicId_.thanks'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysNewRoute = SurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SPublicIdRoute = SPublicIdRouteImport.update({
  id: '/s/$publicId',
  path: '/s/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIdResponsesRoute = SurveysIdResponsesRouteImport.update({
  id: '/surveys/$id/responses',
  path: '/surveys/$id/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysIdEditRoute = SurveysIdEditRouteImport.update({
  id: '/surveys/$id/edit',
  path: '/surveys/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const SPublicIdThanksRoute = SPublicIdThanksRouteImport.update({
  id: '/s/$publicId_/thanks',
  path: '/s/$publicId/thanks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/s/$publicId': typeof SPublicIdRoute
  '/surveys/new': typeof SurveysNewRoute
  '/s/$publicId/thanks': typeof SPublicIdThanksRoute
  '/surveys/$id/edit': typeof SurveysIdEditRoute
  '/surveys/$id/responses': typeof SurveysIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/s/$publicId': typeof SPublicIdRoute
  '/surveys/new': typeof SurveysNewRoute
  '/s/$publicId/thanks': typeof SPublicIdThanksRoute
  '/surveys/$id/edit': typeof SurveysIdEditRoute
  '/surveys/$id/responses': typeof SurveysIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/s/$publicId': typeof SPublicIdRoute
  '/surveys/new': typeof SurveysNewRoute
  '/s/$publicId_/thanks': typeof SPublicIdThanksRoute
  '/surveys/$id/edit': typeof SurveysIdEditRoute
  '/surveys/$id/responses': typeof SurveysIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/auth/verify'
    | '/s/$publicId'
    | '/surveys/new'
    | '/s/$publicId/thanks'
    | '/surveys/$id/edit'
    | '/surveys/$id/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/auth/verify'
    | '/s/$publicId'
    | '/surveys/new'
    | '/s/$publicId/thanks'
    | '/surveys/$id/edit'
    | '/surveys/$id/responses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/auth/verify'
    | '/s/$publicId'
    | '/surveys/new'
    | '/s/$publicId_/thanks'
    | '/surveys/$id/edit'
    | '/surveys/$id/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  SPublicIdRoute: typeof SPublicIdRoute
  SurveysNewRoute: typeof SurveysNewRoute
  SPublicIdThanksRoute: typeof SPublicIdThanksRoute
  SurveysIdEditRoute: typeof SurveysIdEditRoute
  SurveysIdResponsesRoute: typeof SurveysIdResponsesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/new': {
      id: '/surveys/new'
      path: '/surveys/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof SurveysNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$publicId': {
      id: '/s/$publicId'
      path: '/s/$publicId'
      fullPath: '/s/$publicId'
      preLoaderRoute: typeof SPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$id/responses': {
      id: '/surveys/$id/responses'
      path: '/surveys/$id/responses'
      fullPath: '/surveys/$id/responses'
      preLoaderRoute: typeof SurveysIdResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys/$id/edit': {
      id: '/surveys/$id/edit'
      path: '/surveys/$id/edit'
      fullPath: '/surveys/$id/edit'
      preLoaderRoute: typeof SurveysIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$publicId_/thanks': {
      id: '/s/$publicId_/thanks'
      path: '/s/$publicId/thanks'
      fullPath: '/s/$publicId/thanks'
      preLoaderRoute: typeof SPublicIdThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  SPublicIdRoute: SPublicIdRoute,
  SurveysNewRoute: SurveysNewRoute,
  SPublicIdThanksRoute: SPublicIdThanksRoute,
  SurveysIdEditRoute: SurveysIdEditRoute,
  SurveysIdResponsesRoute: SurveysIdResponsesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
